files:
  - source: Localization/
    translation: Localization/%language%/Localizable.strings
    languages_mapping:
      language:
        zh-CN: zh-Hans
        fr: fr
        de: de
        ja: ja
        ko: ko
        es-ES: es
        
  -  source: /GemWallet/Localization/en.lproj/Localizable.strings
      translation: /GemWallet/Localization/%osx_code%/%original_file_name%

  -  source: /GemWallet/Localization/en.lproj/*.html
      translation: /GemWallet/Localization/%osx_code%/%original_file_name%

